# Generated by Django 5.1.2 on 2025-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypartner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.IntegerField(),
        ),
    ]
