# Generated by Django 5.1.2 on 2025-03-31 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypartner', '0003_studentprogress_delete_quiz_delete_studymaterial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('hero', 'Who is your favorite hero?'), ('food', 'What is your favorite food?'), ('city', 'In which city were you born?'), ('pet', 'What was the name of your first pet?'), ('school', 'What was the name of your first school?'), ('email', 'What is your email address?')], max_length=50)),
                ('answer', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
